version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root123!
      - MYSQL_DATABASE=auth_system
      - JWT_SECRET=12c9a3d4c34b8a57d1f3c9b4892db9f84e2595b05688b2ef9c79e42d40f687f4
      - GOOGLE_CLIENT_ID=your-client-id
      - GOOGLE_CLIENT_SECRET=your-client-secret
      - GITHUB_CLIENT_ID=your-client-id
      - GITHUB_CLIENT_SECRET=your-client-secret
    depends_on:
      - db
    restart: always
  
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root123!
      MYSQL_DATABASE: auth_system
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
